/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VehicleRentalSystem;

/**
 *
 * @author maxwe
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class VehicleRentalSystem extends javax.swing.JFrame {
    public VehicleRentalSystem() {
        initComponents();
    }


    /**
     * Creates new form VehicleRentalSystem
     * /
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //----------------------------------------------------------------------------------------------------
    
        public void fetchAndDisplayCustomerData() {
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0); // clear existing rows

        try {
            // 1. Connect to MySQL
            Connection customerCon = ConnectionProvider.getCon();
            // 2. SQL query
            String sql = "SELECT * FROM customer_details";
            Statement stmt = customerCon.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            // 3. Loop through results
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("ID"),
                    rs.getString("Name"),
                    rs.getString("Surname"),
                    rs.getString("Address"),
                    rs.getString("VehicleNumber"),
                };
                model.addRow(row);
            }

            // 4. Close connections
            rs.close();
            stmt.close();
            customerCon.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }
    //----------------------------------------------------------------------------------------    
    public void fetchAndDisplayVehicleData(){
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        
        try{
            Connection vehicleCon = ConnectionProvider.getCon2();
            
            String query = "SELECT * FROM vehicles";
            Statement sendQuery = vehicleCon.createStatement();
            ResultSet processedQuery = sendQuery.executeQuery(query);
            
            while(processedQuery.next()){
                Object[] record = {
                    processedQuery.getString("vehicleNumber"),
                    processedQuery.getString("vehicleName"),
                    processedQuery.getString("colour"),
                    processedQuery.getString("Status"),
                
                };
                model.addRow(record);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }    

    //----------------------------------------------------------------------------------------------------
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtSurname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtRentedVehicleNum = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxtAddVehicleNum = new javax.swing.JTextField();
        jtxtVehicleName = new javax.swing.JTextField();
        jtxtColour = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vehicleDelete = new javax.swing.JButton();
        customerAdd = new javax.swing.JButton();
        customerDelete = new javax.swing.JButton();
        vehicleFormReset = new javax.swing.JButton();
        vehicleAdd = new javax.swing.JButton();
        customerFormReset = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jBtnShowVehicleRecords = new javax.swing.JButton();
        jBtnShowCustomerRecords = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 7, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 7, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Rent A Vehicle");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, -1, -1));

        jLabel4.setText("Cstomer Details");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jtxtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIDActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 71, 231, -1));

        jLabel5.setText("Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 20));
        jPanel2.add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 231, -1));

        jLabel6.setText("Surname");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 20));
        jPanel2.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 231, -1));

        jLabel7.setText("Address");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 20));
        jPanel2.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 231, -1));

        jLabel8.setText("Vehicle Number");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 20));
        jPanel2.add(jtxtRentedVehicleNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 231, -1));

        jLabel13.setText("ID");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 440, 290));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vehicle Number", "Vehicle Name", "Colour", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 520, 241));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Surname", "Address", "Vehicle Number"
            }
        ));
        jTable3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 520, 250));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 7, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Add New Vehicle");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, -1, -1));
        jPanel3.add(jtxtAddVehicleNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 231, -1));
        jPanel3.add(jtxtVehicleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 231, -1));
        jPanel3.add(jtxtColour, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 231, -1));

        jLabel16.setText("Vehicle Number");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 20));

        jLabel17.setText("Name");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 20));

        jLabel18.setText("colour");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 440, 220));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Vehicle Management System");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel1)
                .addContainerGap(386, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1210, -1));

        vehicleDelete.setText("Delete");
        vehicleDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(vehicleDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 630, -1, -1));

        customerAdd.setText("Add");
        customerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerAddActionPerformed(evt);
            }
        });
        jPanel1.add(customerAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        customerDelete.setText("Delete");
        customerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(customerDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 330, -1, -1));

        vehicleFormReset.setText("Reset");
        vehicleFormReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleFormResetActionPerformed(evt);
            }
        });
        jPanel1.add(vehicleFormReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, -1, -1));

        vehicleAdd.setText("Add");
        vehicleAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleAddActionPerformed(evt);
            }
        });
        jPanel1.add(vehicleAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, -1));

        customerFormReset.setText("Reset");
        customerFormReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerFormResetActionPerformed(evt);
            }
        });
        jPanel1.add(customerFormReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 153, 255));
        jLabel14.setText("Availabe Vehicles");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 153, 255));
        jLabel15.setText("Rented Vehicles + Customer details");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        jBtnShowVehicleRecords.setText("Show Records");
        jBtnShowVehicleRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShowVehicleRecordsActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnShowVehicleRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 590, -1, -1));

        jBtnShowCustomerRecords.setText("Show Records");
        jBtnShowCustomerRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShowCustomerRecordsActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnShowCustomerRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 290, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1230, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vehicleDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int selectedRow = jTable2.getSelectedRow();
        
        if(selectedRow != -1){
            try {
                String id = (String) model.getValueAt(selectedRow, 0);
                Connection vehicleCon = ConnectionProvider.getCon2();
                PreparedStatement query = vehicleCon.prepareStatement("DELETE FROM vehicles WHERE VehicleNumber = ?");
                
                query.setString(1, id);
                
                query.executeUpdate();
                
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "No row found with that ID.");
            }
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(null, "Row deleted successfully.");  
        }else {
            JOptionPane.showMessageDialog(null, "Please select a row to delete.");
        }
    }//GEN-LAST:event_vehicleDeleteActionPerformed

    private void customerFormResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerFormResetActionPerformed
        jtxtID.setText("");
        jtxtName.setText("");
        jtxtSurname.setText("");
        jtxtAddress.setText("");
        jtxtRentedVehicleNum.setText("");
    }//GEN-LAST:event_customerFormResetActionPerformed

    private void vehicleFormResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleFormResetActionPerformed
        jtxtAddVehicleNum.setText("");
        jtxtVehicleName.setText("");
        jtxtColour.setText("");
    }//GEN-LAST:event_vehicleFormResetActionPerformed

    private void jtxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIDActionPerformed

    private void customerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerAddActionPerformed
       
        String ID = jtxtID.getText();
        String Name = jtxtName.getText();
        String Surname = jtxtSurname.getText();
        String Address = jtxtAddress.getText();
        String VehicleNumber = jtxtRentedVehicleNum.getText();  // Adjusted to match table column
        
        
        try {
            Connection customerCon = ConnectionProvider.getCon();
            Connection vehicleCon = ConnectionProvider.getCon2();
            String query = "INSERT INTO customer_details (ID, Name, Surname, Address, VehicleNumber) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pst = customerCon.prepareStatement(query);
            
            pst.setString(1, ID);
            pst.setString(2, Name);
            pst.setString(3, Surname);
            pst.setString(4, Address);
            pst.setString(5, VehicleNumber);

            pst.executeUpdate();
            
            String select = "SELECT * FROM vehicles.vehicles WHERE VehicleNumber = ?";
            PreparedStatement pstSelect = customerCon.prepareStatement(select);
            pstSelect.setString(1, VehicleNumber);
            ResultSet rs = pstSelect.executeQuery();
            
            if(rs.next()){
                String updateQuery = "UPDATE vehicles.vehicles SET Status = 'Unavailable' WHERE VehicleNumber = ?";
                PreparedStatement pstUpdate = vehicleCon.prepareStatement(updateQuery);
                pstUpdate.setString(1, VehicleNumber);
                
                int rowsAffected = pstUpdate.executeUpdate();
                
                if (rowsAffected > 0) {
                    System.out.println("Status updated to 'Unavailable' for vehicle number: " + VehicleNumber);
                } else {
                    System.out.println("No update was made.");
                }
            }
            fetchAndDisplayCustomerData();    
            JOptionPane.showMessageDialog(null, "Customer successfully added.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_customerAddActionPerformed

    private void vehicleAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleAddActionPerformed
        String vehicleNumber = jtxtAddVehicleNum.getText();
        String vehicleName = jtxtVehicleName.getText();
        String colour = jtxtColour.getText();
        String status = "Available";
        
        try{
            Connection vehicleCon = ConnectionProvider.getCon2();
            
            String check = "SELECT * FROM vehicles.vehicles WHERE VehicleNumber = ?";
            PreparedStatement pstCheck = vehicleCon.prepareStatement(check);
            pstCheck.setString(1, vehicleNumber);
            ResultSet rs = pstCheck.executeQuery();
            
            if(rs.next()){
                String change = "UPDATE vehicles.vehicles SET Status = 'Availabe' WHERE VehicleNumber = ?";
                PreparedStatement pstChange = vehicleCon.prepareStatement(change);
                pstChange.setString(1, vehicleNumber);
                
                int rowsAffected = pstChange.executeUpdate();
                
                if (rowsAffected > 0) {
                    System.out.println("Status updated to 'Available' for vehicle number: " + vehicleNumber);
                } else {
                    System.out.println("No update was made.");
                }
            }else {
                    
                String query = "INSERT INTO vehicles (vehicleNumber, vehicleName, colour, status) VALUES (?, ?, ?, ?)";
                PreparedStatement pst = vehicleCon.prepareStatement(query);

                pst.setString(1, vehicleNumber);    // Set value for first '?'
                pst.setString(2, vehicleName);         // Set value for second '?'
                pst.setString(3, colour);   // Set value for third '?'
                pst.setString(4, status);

                pst.executeUpdate();            // Run the query

             }
            
            fetchAndDisplayVehicleData();
            JOptionPane.showMessageDialog(null, "Successfully Updated");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Student id already exists");
            
        }
    }//GEN-LAST:event_vehicleAddActionPerformed

    private void jTable3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3AncestorAdded

    private void customerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        int selectedRow = jTable3.getSelectedRow();
        
        if (selectedRow != -1){
            try{
                int id = (int) model.getValueAt(selectedRow, 0);
                Connection customerCon = ConnectionProvider.getCon();
                String query = "DELETE FROM customer_details WHERE ID = ?";

                PreparedStatement pstmt = customerCon.prepareStatement(query);
                pstmt.setInt(1, id);
                
                pstmt.executeUpdate();
             
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "No row found with that ID.");
            }
        model.removeRow(selectedRow);
        JOptionPane.showMessageDialog(null, "Row deleted successfully.");    
        }else {
            JOptionPane.showMessageDialog(null, "Please select a row to delete.");
        }
    }//GEN-LAST:event_customerDeleteActionPerformed

    private void jBtnShowVehicleRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShowVehicleRecordsActionPerformed
        fetchAndDisplayVehicleData();
    }//GEN-LAST:event_jBtnShowVehicleRecordsActionPerformed

    private void jBtnShowCustomerRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShowCustomerRecordsActionPerformed
        fetchAndDisplayCustomerData();    
    }//GEN-LAST:event_jBtnShowCustomerRecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleRentalSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleRentalSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleRentalSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleRentalSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleRentalSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerAdd;
    private javax.swing.JButton customerDelete;
    private javax.swing.JButton customerFormReset;
    private javax.swing.JButton jBtnShowCustomerRecords;
    private javax.swing.JButton jBtnShowVehicleRecords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jtxtAddVehicleNum;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtColour;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtRentedVehicleNum;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtVehicleName;
    private javax.swing.JButton vehicleAdd;
    private javax.swing.JButton vehicleDelete;
    private javax.swing.JButton vehicleFormReset;
    // End of variables declaration//GEN-END:variables
}
